apiVersion: apps/v1
kind: Deployment
metadata:
  name: wineq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wineq
  template:
    metadata:
      labels:
        app: wineq
    spec:
      containers:
      - name: wineq
        image: gcr.io/hft-demo-v1/wineq:v1
        ports:
        - containerPort: 5001